### ISSUE TITLE
password protection per room

### ISSUE THREAD

**Issue by devdrik** [Shot-Clock-DLaxV/shotclock-web#1]
As a user I want to be the only person to have access to the controls of the shot clock

**Comment by ChangeD20** [comment]
In combination with change room names to generated 4-digit ID codes the Passwort could also be a generated 4-digit ID code. You only need the code to get to the controller page for each shot clock room. So you could add the Passwort to the controller link to get into the room, so the Passwort would be distributed automatically if needed. The display page should be free in all cases.

**Comment by tobire** [comment]
Everything fixed/changed in the rewritten version: https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
