### ISSUE TITLE
button alignment right on start screen

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#12]

**Comment by ChangeD20** [comment]
Hendrik

**Comment by ChangeD20** [comment]
![image](https://user-images.githubusercontent.com/69245786/151697995-036754a4-7e19-4c3d-beb5-b8e17580b387.jpeg)

**Comment by tobire** [comment]
Completely redesigned in the new version, so these buttons don't exist in this form anymore: https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
