### ISSUE TITLE
Double/multi tap/click makes the clock counting faster and Lead to chrashs

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#13]

**Comment by ChangeD20** [comment]
On pc an Smartphone

**Comment by ChangeD20** [comment]
Doubles counting speed, stackable effect

**Comment by tobire** [comment]
Fixed in rewritten version: https://github.com/Shot-Clock-DLaxV/shotclock-web-server / shotclock.dlaxv.de
