### ISSUE TITLE
Controller: number and reset Button Touch

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#14]
Hendrik

Oneplus 5t

Android

Chrome

![image](https://user-images.githubusercontent.com/69245786/151698035-5fb369c5-8180-468e-ae35-568395d64575.jpeg)

**Comment by tobire** [comment]
Completely redesigned in the new version, so these buttons have a different layout now: https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
