### ISSUE TITLE
To long instructions

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#15]
Make usage easier

- Don't use self choosen room names, instead use of generated 4-digits ID codes

- Make a share button for the links

**Comment by ChangeD20** [comment]
From sebi

**Comment by ChangeD20** [comment]
- Make the audio information icon a button to choose audio on/off, the icon is misleading

**Comment by tobire** [comment]
Everything fixed/changed in the rewritten version: https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
