### ISSUE TITLE
Startpage: add ID code insert field to join a room

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#16]
Now you need the link to join the room. To navigate to a existing room from the startpage you need to create the room with the known name again to get to the join button

**Comment by ChangeD20** [comment]
From sebi

**Comment by ChangeD20** [comment]
- Enter as hotkey for startpage to sign in a room after insert of a id

**Comment by ChangeD20** [comment]
User should have an button for create and join

**Comment by tobire** [comment]
Everything fixed/changed in the rewritten version: https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
