### ISSUE TITLE
Startpage: make the info pop ups hideable by interaction of the user

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#17]
Now the user has to wait too long, the user wants to choose how long the are visible

**Comment by ChangeD20** [comment]
From sebi

**Comment by tobire** [comment]
Info popups don't exist in the rewritten version (for now): https://github.com/Shot-Clock-DLaxV/shotclock-web-client / shotclock.dlaxv.de
