### ISSUE TITLE
change current time of the shotclock

### ISSUE THREAD

**Issue by devdrik** [Shot-Clock-DLaxV/shotclock-web#3]
As a user I want to be able to change the time on the clock im case something went wrong

**Comment by tobire** [comment]
I also want to be able to change the start time to which the clock gets reset after it runs out

**Comment by tobire** [comment]
Moved to https://github.com/Shot-Clock-DLaxV/shotclock-web-server/issues/2 and https://github.com/Shot-Clock-DLaxV/shotclock-web-client/issues/3
