### ISSUE TITLE
Better "How To" Section

### ISSUE THREAD

**Issue by ChangeD20** [Shot-Clock-DLaxV/shotclock-web#7]
As a user I want to have a better description in which use-cases and setups I can use this app and how to use it.

**Comment by ChangeD20** [comment]
"?" button next to all buttons with pup-up instructions for easy understanding

**Comment by tobire** [comment]
Info Page and Info Popups next to Room buttons implemented.
Info page might still need some rework on the content depending on feedback from outsiders.

**Comment by tobire** [comment]
Moved to https://github.com/Shot-Clock-DLaxV/shotclock-web-client/issues/2
